# Generated by Django 6.0.5 on 2026-05-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_aboutcontent_herocontent_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='e.g., fa-linkedin, fa-instagram', max_length=50)),
            ],
        ),
    ]
