# Generated by Django 6.0.5 on 2026-05-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='titles',
            field=models.CharField(default='Software Engineer, Maker, Designer', help_text='Separate with commas for the cycling effect', max_length=255),
        ),
    ]
