# Generated by Django 6.0.5 on 2026-05-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_herocontent_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Dark', max_length=50)),
                ('bg_color', models.CharField(default='#0c0c0e', help_text='Hex code for background', max_length=7)),
                ('accent_color', models.CharField(default='#a78bfa', help_text='Hex code for accents', max_length=7)),
                ('card_color', models.CharField(default='#161619', help_text='Hex code for cards', max_length=7)),
                ('text_color', models.CharField(default='#f4f4f5', help_text='Hex code for primary text', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
