# Generated by Django 6.0.5 on 2026-05-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_themesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload custom icon image/SVG', null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='bg_pattern',
            field=models.CharField(choices=[('none', 'Solid Color'), ('dots', 'Dotted Grid'), ('grid', 'Square Grid')], default='dots', max_length=10),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(blank=True, help_text='FontAwesome class e.g., fa-linkedin', max_length=50),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='accent_color',
            field=models.CharField(default='#a78bfa', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='bg_color',
            field=models.CharField(default='#0c0c0e', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='card_color',
            field=models.CharField(default='#161619', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='text_color',
            field=models.CharField(default='#f4f4f5', max_length=7),
        ),
    ]
