# Generated by Django 6.0.5 on 2026-05-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_sociallink_icon_image_themesettings_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='bg_image_blur',
            field=models.IntegerField(default=0, help_text='Blur in pixels'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='bg_image_brightness',
            field=models.FloatField(default=1.0, help_text='Brightness (e.g., 0.5 for dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='bg_pattern_color',
            field=models.CharField(default='#ffffff', help_text='Color for the grid/dots', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='bg_pattern_opacity',
            field=models.FloatField(default=0.05, help_text='Opacity (0.0 to 1.0)'),
        ),
    ]
