# Generated by Django 6.0.5 on 2026-05-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_themesettings_bg_image_blur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='anim_speed',
            field=models.FloatField(default=0.6, help_text='Animation duration in seconds (e.g., 0.6)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='typing_speed',
            field=models.IntegerField(default=150, help_text='Typing speed in milliseconds (e.g., 150)'),
        ),
    ]
