# Generated by Django 6.0.5 on 2026-05-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_themesettings_anim_speed_themesettings_typing_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a custom logo for the navigation bar', null=True, upload_to='logos/'),
        ),
    ]
