# Generated by Django 6.0.5 on 2026-05-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_themesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload a custom browser icon (favicon)', null=True, upload_to='favicons/'),
        ),
    ]
