# Generated by Django 6.0.5 on 2026-05-10 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Upload a custom browser icon (PNG, JPG, SVG, ICO)', null=True, upload_to='favicons/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'ico'])]),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='logo',
            field=models.FileField(blank=True, help_text='Upload a custom logo (PNG, JPG, or SVG)', null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])]),
        ),
    ]
