# Generated by Django 6.0.5 on 2026-05-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_themesettings_favicon_alter_themesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='card_border_radius',
            field=models.IntegerField(default=24, help_text='Border radius for cards (px)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='container_width',
            field=models.IntegerField(default=1200, help_text='Maximum width of the website container (px)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='glass_blur',
            field=models.IntegerField(default=15, help_text='Blur intensity for glass effects (px)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='grid_column_width',
            field=models.IntegerField(default=320, help_text='Minimum width of grid items (px)'),
        ),
    ]
