# Generated by Django 6.0.5 on 2026-05-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_themesettings_card_border_radius_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_part_1', models.CharField(default='PORT', max_length=50)),
                ('logo_part_2', models.CharField(default='FOLIO', max_length=50)),
                ('nav_home', models.CharField(default='Home', max_length=50)),
                ('nav_projects', models.CharField(default='Projects', max_length=50)),
                ('nav_about', models.CharField(default='About', max_length=50)),
                ('nav_references', models.CharField(default='References', max_length=50)),
                ('nav_admin', models.CharField(default='Admin', max_length=50)),
                ('nav_contact', models.CharField(default='Contact', max_length=50)),
                ('footer_copyright', models.CharField(default='SERHAT ÇAM', max_length=100)),
                ('footer_tagline', models.CharField(default='Crafted with Django & Passion.', max_length=200)),
                ('projects_title_prefix', models.CharField(default='All', max_length=50)),
                ('projects_title_highlight', models.CharField(default='Projects', max_length=50)),
                ('contact_title_prefix', models.CharField(default='Get in', max_length=50)),
                ('contact_title_highlight', models.CharField(default='Touch', max_length=50)),
                ('contact_description', models.TextField(default='Have a project in mind or just want to say hi? Drop me a message below.')),
                ('references_title_prefix', models.CharField(default='Kind', max_length=50)),
                ('references_title_highlight', models.CharField(default='Words', max_length=50)),
                ('skills_title_prefix', models.CharField(default='Expertise', max_length=50)),
                ('skills_title_highlight', models.CharField(default='& Tech', max_length=50)),
                ('skills_sub_label', models.CharField(default='My Skills', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
