# Generated by Django 6.0.5 on 2026-05-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_email',
            field=models.EmailField(default='hello@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_location',
            field=models.CharField(default='New York, USA', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_phone',
            field=models.CharField(default='+1 (234) 567-890', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_social_text',
            field=models.CharField(default='Follow me on social media', max_length=100),
        ),
    ]
