# Generated by Django 6.0.5 on 2026-05-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_siteconfiguration_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='light_accent_color',
            field=models.CharField(default='#7c3aed', help_text='Light mode accent color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='light_bg_color',
            field=models.CharField(default='#ffffff', help_text='Light mode background color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='light_bg_pattern_color',
            field=models.CharField(default='#000000', help_text='Light mode pattern color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='light_card_color',
            field=models.CharField(default='#f4f4f5', help_text='Light mode card color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='light_text_color',
            field=models.CharField(default='#18181b', help_text='Light mode primary text color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='light_text_secondary_color',
            field=models.CharField(default='#52525b', help_text='Light mode secondary text color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='text_secondary_color',
            field=models.CharField(default='#a1a1aa', help_text='Dark mode secondary text color', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='accent_color',
            field=models.CharField(default='#a78bfa', help_text='Dark mode accent color', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='bg_color',
            field=models.CharField(default='#0c0c0e', help_text='Dark mode background color', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='card_color',
            field=models.CharField(default='#161619', help_text='Dark mode card color', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='text_color',
            field=models.CharField(default='#f4f4f5', help_text='Dark mode primary text color', max_length=7),
        ),
    ]
