# Generated by Django 6.0.5 on 2026-05-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_themesettings_light_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='container_padding_top',
            field=models.FloatField(default=2.0, help_text='Top padding for the main container (rem)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='hero_gap',
            field=models.FloatField(default=3.0, help_text='Gap between elements in the hero section (rem)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='nav_padding_y',
            field=models.FloatField(default=0.8, help_text='Vertical padding for the navbar (rem)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='section_padding_y',
            field=models.FloatField(default=3.0, help_text='Vertical padding for sections (rem)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_accent_color',
            field=models.CharField(default='#8b5cf6', help_text='Light mode accent color', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_bg_color',
            field=models.CharField(default='#fafafa', help_text='Light mode background color', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_bg_pattern_color',
            field=models.CharField(default='#e5e7eb', help_text='Light mode pattern color', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_card_color',
            field=models.CharField(default='#ffffff', help_text='Light mode card color', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_text_color',
            field=models.CharField(default='#111827', help_text='Light mode primary text color', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_text_secondary_color',
            field=models.CharField(default='#4b5563', help_text='Light mode secondary text color', max_length=7),
        ),
    ]
