# Generated by Django 6.0.5 on 2026-05-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_themesettings_container_padding_top_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='years_of_experience',
            field=models.IntegerField(default=1),
        ),
    ]
