# Generated by Django 6.0.5 on 2026-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_aboutcontent_image_aboutcontent_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='hero_gap',
            field=models.FloatField(default=1.0, help_text='Gap between elements in the hero section (rem)'),
        ),
    ]
