# Generated by Django 6.0.5 on 2026-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_themesettings_hero_gap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='logo_part_1',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='card_border_radius',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='container_padding_top',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='container_width',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='glass_blur',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='grid_column_width',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='hero_gap',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='nav_padding_y',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='section_padding_y',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='card_border_radius',
            field=models.IntegerField(default=24, help_text='Border radius for cards (px)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='container_padding_top',
            field=models.FloatField(default=2.0, help_text='Top padding for the main container (rem)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='container_width',
            field=models.IntegerField(default=1200, help_text='Maximum width of the website container (px)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='glass_blur',
            field=models.IntegerField(default=15, help_text='Blur intensity for glass effects (px)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='grid_column_width',
            field=models.IntegerField(default=320, help_text='Minimum width of grid items (px)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_gap',
            field=models.FloatField(default=1.0, help_text='Gap between elements in the hero section (rem)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='nav_padding_y',
            field=models.FloatField(default=0.8, help_text='Vertical padding for the navbar (rem)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='section_padding_y',
            field=models.FloatField(default=3.0, help_text='Vertical padding for sections (rem)'),
        ),
    ]
