# Generated by Django 6.0.5 on 2026-05-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_remove_siteconfiguration_logo_part_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo_part_1',
            field=models.CharField(default='PORT', max_length=50),
        ),
    ]
